#!/bin/bash

mkdir -p build/test-runtime/
qemu-system-x86_64 -s -smp 4 -serial vc -serial file:build/test-runtime/serial \
	-d cpu_reset,int -m 16G -monitor stdio \
	-drive format=raw,file=build/modulos.img,if=ide,media=disk \
	-smbios type=0,uefi=on -bios /usr/share/qemu/OVMF.fd \
	-device VGA

